[project]
authors = ["Hernan Grecco <hgrecco@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "smartexp"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"
numpy = "*"
scipy = "*"
matplotlib = "*"
jupyter = ">=1.1.1,<2"
